version: "3.4"

services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rails-db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  rails-db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rails-db-admin: # Setup guide: https://linuxhint.com/postgresql_docker/
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "rails-db:pgsql-server"

volumes:
  gem_cache:
  db_data:
  node_modules:
  pgadmin-data:
